// <auto-generated />
namespace TryAgain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fansmig3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fansmig3));
        
        string IMigrationMetadata.Id
        {
            get { return "201711082046403_fansmig3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
