// <auto-generated />
namespace TryAgain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class comAndPstMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comAndPstMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201711182123084_comAndPstMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
